### ISSUE TITLE
Feature upgrade.

### ISSUE THREAD

**Issue by Mohd-Imtiyaz** [tamaraiselvan/Base-Django-project-Setup#2]
Please create edit profiles options and deactive account feature as soon as possible in the profile page.

I am waiting for that feature.
Please provide with slight security fixes in profile section.

Thank you!
I hope you consider my request and do the needful.

**Comment by tamaraiselvan** [comment]
Surely I will consider your upgrade features and the feature you asked is under development.

I will give much security features than you expect in the profile page of the users.

Soon you can expect that release.

Thank you for your suggesstions. if any thing else please create a issue and notify me.

Thank you once again.

**Comment by tamaraiselvan** [comment]
Your requested feature is pushed in the latest update.

Please check the code here: [Version 3 - v3.0](https://github.com/tamaraiselvan/Base-django-project-Setup/releases/tag/v3.0)
